# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_birth_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='random_number',
            field=models.PositiveIntegerField(default=user.models.random_value),
        ),
    ]
